### ISSUE TITLE
Link da fatura na notifição de Nova fatura de serviço

### ISSUE THREAD

**Issue by ubamicrosinformatica** [LinkNacional/whmcs-whatsapp-api-notifications-open-source#32]
Precisa ter a variável de link da fatura pdf na notificação  de "Nova fatura de serviço"

todas vez que for criado uma fatura mensal do serviço do cliente , ir pelo whatsApp a notificação de nova fatura de serviço , com o link pdf desta fatura , atualmente só tem no lembrete de fatura Pdf para enviar manual e não tem automático.... faz muita falta , é estranho chegar todo mes automático para o cliente sem. o link da fatura.....

uma coisa que faz muita falta também e não tem. em nenhuma notificação , é a variavel de Valor , não tem como inserir em nenhum o valor do serviço.

serial possível esta implantação?

**Comment by brunoferreiralkn** [comment]
Bom dia, @ubamicrosinformatica.

Obrigado pela contribuição com ideias para o módulo.

Até sexta feira (10/11) vamos retornar com as funcionalidades solicitadas:
- Nova notificação para envio automático de nova fatura com Link de PDF (analisar se é possível enviar o PDF anexado).
- Adicionar parâmetros Balanço da fatura e Valor da fatura às notificações referentes a faturas.

**Comment by brunoferreiralkn** [comment]
@ubamicrosinformatica

Por favor, realize o download da nova versão do módulo clicando [aqui](https://cliente.linknacional.com.br/dl.php?type=d&id=34).

Depois, realize o download das notificações [aqui](https://github.com/LinkNacional/whmcs-whatsapp-api-notifications-open-source/releases/download/v3.3.0/notifications.zip).

Por último, via FTP, apague a instalação anterior do módulo envie a nova versão para o seu WHMCS, depois envie as novas notificações.

**Comment by ubamicrosinformatica** [comment]
Boa tarde , maravilha esta atualização , eu fiz todo o pocedimento , apareceu as variáveis agora show de bola, porém oque ocorre é que não está mais criando fatura nova em serviços já criados , eu testo forçando a cron com --force pra ver se tá tudo certinho porém nesta nova versão não está mais criando fatura da opção: Nova fatura de serviço

teria como dar uma olhada ?

**Comment by ubamicrosinformatica** [comment]
Erro na Notificação de Nova fatura Criada Serviço , não está enviando Nova fatura de serviço criado após a atualização, e gostaria de saber se dá pra colocar o link da fatura pdf também no template Fatura com 6 dias de atraso, faltou nesse template a função de link da fatura PDF e valores.. muito importante ter....

**Comment by brunoferreiralkn** [comment]
Boa tarde, @ubamicrosinformatica.

A notificação **Nova fatura de serviço** só é executada quando as condições abaixo são atendidas:
- A fatura foi criada automaticamente pelo sistema do WHMCS.
- A fatura não está relacionada a um pedido novo.
- For identificado algum serviço nos itens da fatura.

**Comment by brunoferreiralkn** [comment]
@ubamicrosinformatica, por favor, realize o [download e a instalação da correção aqui](https://github.com/LinkNacional/whmcs-whatsapp-api-notifications-open-source/releases/download/v3.3.1/notifications.zip).

**Comment by ubamicrosinformatica** [comment]
Boa tarde, funcionou certinho agora , obrigado pela correção e parabéns pela atenção, seria possível fazer a opção de link. da fatura pdf na notificação de lembrete 6 dias ? ficaria espetacular ...

**Comment by brunoferreiralkn** [comment]
@ubamicrosinformatica, adicionamos esse parâmetro a notificação **Fatura com 6 dias de atraso** juntamente com a correção.

Basta subir a nova versão da pasta **Invoice6DaysLate** que está no [zip que enviei](https://github.com/LinkNacional/whmcs-whatsapp-api-notifications-open-source/releases/download/v3.3.1/notifications.zip) no comentário anterior.

**Comment by ubamicrosinformatica** [comment]
Ficou excelente o link pdf agora  ,mas ainda faltou um parametro importante que é a data de vencimento, tem. como. adicionar ? ai ficaria completo a notificação de fatura com 6 dias...

**Comment by brunoferreiralkn** [comment]
Bom dia, @ubamicrosinformatica.

Implementamos o parâmetro de data de vencimento da fatura à notificação **Fatura com 6 dias de atraso**, como solicitado.

Por favor, [realize o download aqui](https://github.com/LinkNacional/whmcs-whatsapp-api-notifications-open-source/releases/download/v3.3.2/notifications.zip) e realize a instalação da notificação Invoice6DaysLate.

**Comment by ubamicrosinformatica** [comment]
Maravilha funcionou perfeito. agora , parabéns pela atenção e dedicação na solução
