### ISSUE TITLE
Error instalacion

### ISSUE THREAD

**Issue by rodrigoj78** [LinkNacional/whmcs-whatsapp-api-notifications-open-source#33]
Good morning, I want to install the WhatsApp module for whmcs but when I want to load it according to the instructions, whmcs does not detect it.
I put it in the addon folder and when I unzip it, it gives an error in whmcs

Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

Whoops\Exception\ErrorException: The file /............../modules/addons/lknhooknotification/lknhooknotification.php encoded as type [1/81] cannot be decoded by this version of the ionCube Loader.
in Unknown:0
Stack trace:
#0 /........../vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(16, 'The file /home/...', 'Unknown', 0)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

**Comment by brunoferreiralkn** [comment]
Hello @rodrigoj78. The module requires **PHP 8.1** and **IonCube Loader 12.0**.

Your WHMCS needs to be at version 8.6 for IonCube to be at version 12.0.

https://docs.whmcs.com/IonCube_Loader_Version_Matrix

**Comment by brunoferreiralkn** [comment]
Closing the issue due to lack of feedback.
