### ISSUE TITLE
Notifição Fatura paga ( Recibo )

### ISSUE THREAD

**Issue by ubamicrosinformatica** [LinkNacional/whmcs-whatsapp-api-notifications-open-source#38]
Seria possível criar um template de Notificação WhatsApp para quando o whmcs acionar o Invoice Payment Confirmation , fazer enviar ao cliente por whatsApp o seguinte:

Olá **Nome do cliente** ! Informamos que o pagamento de sua fatura N° **id da fatura**, foi confirmado com sucesso, o comprovante de pagamento foi enviado para seu e-mail: **e-mail do cliente**, obrigado pelo pagamento.

Usar variável : nome do cliente , id da fatura e e-mail do cliente

**Comment by brunoferreiralkn** [comment]
Bom dia, @ubamicrosinformatica.

Dentro de duas semanas vamos lançar a implementação.

Iremos lançar a nova notificação com os parâmetros existentes atuais mais os solicitados.

**Comment by ubamicrosinformatica** [comment]
Boa noite, maravilha , aguardaremos essa implementação que vai facilitar muito.

**Comment by brunoferreiralkn** [comment]
@ubamicrosinformatica, por favor, [realize o download da notificação InvoicePaid clicando aqui](https://github.com/LinkNacional/whmcs-whatsapp-api-notifications-open-source/releases/download/v3.4.0/notifications.zip).

Caso encontre problemas, nos envie os logs gerados pelo módulo.

**Comment by ubamicrosinformatica** [comment]
Boa tarde , fiz o download , e ja configurei o template de Fatura Paga no Meta e já configurei também no Whmcs, e ja fiz 2 testes e não deu , fiz pagamento manual pelo Whmcs admin, foi o e-mail mas não foi comprovante pelo whatsApp , fiz pagamento automático pagando pix  e também não foi comprovante pelo Whatsapp , o email de confirmação de pagamento chega no cliente , mas o whatsApp não, além do download da notificação tem que atualizar o modulo também? pois não está aparecendo para atualizar o. módulo...

**Comment by brunoferreiralkn** [comment]
Bom dia, @ubamicrosinformatica.

Perdão pelo imprevisto, por favor, siga a instrução abaixo:

Por favor, [realizem o download das notificações aqui](https://github.com/LinkNacional/whmcs-whatsapp-api-notifications-open-source/releases/download/v3.5.0/notifications.zip) e atualize a notificação **InvoicePaid:**

**Comment by ubamicrosinformatica** [comment]
Bruno ficou perfeito o Recibo , funcionando certinho agora, quando paga a fatura o cliente recebe via whatsapp o recibo.
