### ISSUE TITLE
Alterar a URL da mensagem privada do chatwoot

### ISSUE THREAD

**Issue by gabriell-prado** [LinkNacional/whmcs-whatsapp-api-notifications-open-source#43]
Bom dia!
Estou testando o modulo de notificações para automação de notificações, porém as mensagens da nota privada do chatwoot estão vindo com o link errado aonde faço essa alteração. Estou utilizando um subdomínio. Mas o link vem sem o subdomínio.

**Comment by gabriell-prado** [comment]
Eu queria também alterar o texto que aparece na nota, deixando idealmente igual a mensagem enviada como eu poderia fazer isso?

**Comment by brunoferreiralkn** [comment]
Boa tarde, @gabriell-prado.

As notificações do WhatsApp utilizam uma notificação do Chatwoot chamada `WhatsAppPrivateNoteNotification`.
Para editar a mensagem que é enviada e verificar como corrigir a URL, [acesse o código fonte aqui](https://github.com/LinkNacional/whmcs-whatsapp-api-notifications-open-source/blob/main/src/modules/addons/lknhooknotification/src/Notifications/Chatwoot/WhatsAppPrivateNote/WhatsAppPrivateNoteNotification.php).

Ficaremos gratos com sua colaboração na correção dessa issue.
Caso você deseje um treinamento especial, você pode contratar nossa hora técnica, [clicando aqui](https://www.linknacional.com.br/contato/).

**Comment by brunoferreiralkn** [comment]
Fechando issue por inatividade.
