### ISSUE TITLE
Alteração do link da private note

### ISSUE THREAD

**Issue by Kaonashiz** [LinkNacional/whmcs-whatsapp-api-notifications-open-source#46]
Boa tarde pessoal, 

estamos com um problema na questão do link que está retornando na WhatsAppPrivateNoteNotification, o link está errado e precisaríamos fazer a mudança do mesmo, vocês conseguem me explicar como podemos fazer essa alteração? Onde fica para fazer a alteração do mesmo?

Desde já, agradeço.

**Comment by brunoferreiralkn** [comment]
Bom dia, @Kaonashiz, há uma issue semelhante ao seu problema.

Por favor, [acesse aqui para saber como mudar o link.](https://github.com/LinkNacional/whmcs-whatsapp-api-notifications-open-source/issues/43)
