### ISSUE TITLE
[BUG] Após instalação não é possível configurar as notificações do ChatWoot

### ISSUE THREAD

**Issue by souzadavi** [LinkNacional/whmcs-whatsapp-api-notifications-open-source#52]
Após instalar ao tentar configurar no menu Chatwoot > Notificações 
![image](https://github.com/LinkNacional/whmcs-whatsapp-api-notifications-open-source/assets/636225/6d58ad35-21b9-4d5f-947e-4a576b503dad)

Aparece o seguinte erro:

![image](https://github.com/LinkNacional/whmcs-whatsapp-api-notifications-open-source/assets/636225/1571e5a1-3491-4b18-8235-a96867384ae5)

**Comment by emanuellopess** [comment]
Issue resolved in new notification module version
