### ISSUE TITLE
[FEATURE] renew domain 5 days before

### ISSUE THREAD

**Issue by souzadavi** [LinkNacional/whmcs-whatsapp-api-notifications-open-source#9]
5 days before domain renew due date  send a message. Last chance to renew your domain.

**Comment by brunoferreiralkn** [comment]
Maybe the module should have a setting where the manager can enter the number of the days rather than fixing it in three days.

What do you think?

**Comment by emanuellopess** [comment]
@brunoferreiralkn I think for it to work it needs a default WhatsApp template with the days as a attribute, what we have is a template for each period.

**Comment by brunoferreiralkn** [comment]
@emanuellopess 
![image](https://user-images.githubusercontent.com/84975603/235922131-568e4974-8c8d-48fb-a413-45ccee7dcf04.png)

We can set "6" dynamically, without having a template for a "hardcoded" day like in the print above.
I mean, other users may take advantage of this feature.

**Comment by brunoferreiralkn** [comment]
Added in 6170b6d79d24d55a042a32e3110407333091a5fc.
